#!/usr/bin/python3
def raise_exception_msg(message=""):
    # Lève une exception de type NameError avec un message personnalisé
    raise NameError(message)
